services:
  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./next-app:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./next-app/.env.local

networks:
  app-network:
    name: pi-motor-de-busca-4-sem_app-network
    driver: bridge